import type { CanonicalRecipe, PantryItem, VisionItem } from '@/lib/schemas';

export const MOCK_PANTRY: Omit<PantryItem, 'id' | 'userId' | 'createdAt'>[] = [
  { name: 'olive oil', category: 'condiments', source: 'manual' },
  { name: 'garlic', category: 'produce', source: 'manual' },
  { name: 'onion', category: 'produce', source: 'manual' },
  { name: 'tomatoes', category: 'produce', source: 'manual' },
  { name: 'eggs', category: 'proteins', source: 'manual' },
  { name: 'butter', category: 'dairy', source: 'manual' },
  { name: 'salt', category: 'pantry_staples', source: 'manual' },
  { name: 'black pepper', category: 'pantry_staples', source: 'manual' },
  { name: 'chicken breast', category: 'proteins', source: 'photo' },
  { name: 'lemon', category: 'produce', source: 'photo' },
  { name: 'parmesan', category: 'dairy', source: 'manual' },
  { name: 'pasta', category: 'grains', source: 'manual' },
  { name: 'basil', category: 'produce', source: 'manual' },
  { name: 'spinach', category: 'produce', source: 'photo' },
];

export const MOCK_VISION_RESULT: VisionItem[] = [
  { name: 'bell pepper', category: 'produce', confidence: 'high' },
  { name: 'mushrooms', category: 'produce', confidence: 'high' },
  { name: 'zucchini', category: 'produce', confidence: 'high' },
  { name: 'cherry tomatoes', category: 'produce', confidence: 'medium', note: 'could be grape tomatoes' },
  { name: 'mozzarella', category: 'dairy', confidence: 'medium', note: 'partially obscured by packaging' },
  { name: 'basil', category: 'produce', confidence: 'low', note: 'could be mint or basil' },
];

export const MOCK_RECIPES: CanonicalRecipe[] = [
  {
    id: 1001,
    title: 'Lemon Garlic Chicken Pasta',
    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600',
    ingredients: [
      { name: 'chicken breast', quantity: 2, unit: 'pieces' },
      { name: 'pasta', quantity: 300, unit: 'g' },
      { name: 'garlic', quantity: 4, unit: 'cloves' },
      { name: 'lemon', quantity: 1, unit: 'whole' },
      { name: 'olive oil', quantity: 3, unit: 'tbsp' },
      { name: 'parmesan', quantity: 50, unit: 'g' },
      { name: 'butter', quantity: 2, unit: 'tbsp' },
      { name: 'salt', quantity: 1, unit: 'tsp' },
      { name: 'black pepper', quantity: 0.5, unit: 'tsp' },
    ],
    ingredientNames: ['chicken breast', 'pasta', 'garlic', 'lemon', 'olive oil', 'parmesan', 'butter', 'salt', 'black pepper'],
    instructions: [
      'Cook pasta according to package directions. Reserve 1 cup pasta water.',
      'Season chicken with salt and pepper. Sear in olive oil until golden, about 6 min per side. Slice.',
      'In the same pan, sauté minced garlic for 30 seconds. Add lemon juice, butter, and pasta water.',
      'Toss pasta in the sauce. Top with sliced chicken, parmesan, and lemon zest.',
    ],
    cuisine: 'italian',
    mealType: 'dinner',
    dietary: ['nut_free', 'soy_free'],
    primaryProtein: 'chicken',
    cookingMethods: ['stovetop'],
    activeTimeMinutes: 20,
    totalTimeMinutes: 30,
    cookTimeBucket: '15_to_30_min',
    difficulty: 'easy',
    spiceLevel: 'none',
    occasion: ['weeknight', 'date_night'],
    servings: 4,
    popularityScore: 0.92,
  },
  {
    id: 1002,
    title: 'Shakshuka',
    imageUrl: 'https://images.unsplash.com/photo-1590412200988-a436970781fa?w=600',
    ingredients: [
      { name: 'eggs', quantity: 6, unit: 'large' },
      { name: 'tomatoes', quantity: 4, unit: 'medium' },
      { name: 'onion', quantity: 1, unit: 'medium' },
      { name: 'garlic', quantity: 3, unit: 'cloves' },
      { name: 'olive oil', quantity: 2, unit: 'tbsp' },
      { name: 'cumin', quantity: 1, unit: 'tsp' },
      { name: 'paprika', quantity: 1, unit: 'tsp' },
      { name: 'salt', quantity: 1, unit: 'tsp' },
      { name: 'feta cheese', quantity: 50, unit: 'g' },
    ],
    ingredientNames: ['eggs', 'tomatoes', 'onion', 'garlic', 'olive oil', 'cumin', 'paprika', 'salt', 'feta cheese'],
    instructions: [
      'Heat olive oil in a large skillet. Sauté diced onion until soft, about 5 minutes.',
      'Add garlic, cumin, and paprika. Cook 1 minute until fragrant.',
      'Add diced tomatoes and simmer 10 minutes until thickened.',
      'Make 6 wells in the sauce. Crack an egg into each well.',
      'Cover and cook 5-7 minutes until whites are set but yolks are still runny.',
      'Crumble feta on top and serve with crusty bread.',
    ],
    cuisine: 'middle_eastern',
    mealType: 'brunch',
    alsoWorksAs: ['breakfast', 'dinner'],
    dietary: ['vegetarian', 'gluten_free', 'nut_free'],
    primaryProtein: 'eggs',
    cookingMethods: ['stovetop'],
    activeTimeMinutes: 15,
    totalTimeMinutes: 25,
    cookTimeBucket: '15_to_30_min',
    difficulty: 'easy',
    spiceLevel: 'mild',
    occasion: ['weeknight', 'comfort_food'],
    servings: 4,
    popularityScore: 0.89,
  },
  {
    id: 1003,
    title: 'Spinach & Garlic Butter Pasta',
    imageUrl: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=600',
    ingredients: [
      { name: 'pasta', quantity: 400, unit: 'g' },
      { name: 'spinach', quantity: 200, unit: 'g' },
      { name: 'garlic', quantity: 5, unit: 'cloves' },
      { name: 'butter', quantity: 60, unit: 'g' },
      { name: 'parmesan', quantity: 80, unit: 'g' },
      { name: 'lemon', quantity: 0.5, unit: 'whole' },
      { name: 'red pepper flakes', quantity: 0.25, unit: 'tsp' },
      { name: 'salt', quantity: 1, unit: 'tsp' },
    ],
    ingredientNames: ['pasta', 'spinach', 'garlic', 'butter', 'parmesan', 'lemon', 'red pepper flakes', 'salt'],
    instructions: [
      'Cook pasta al dente. Reserve 1 cup pasta water before draining.',
      'Melt butter in a large pan. Add sliced garlic and cook until golden, 2 minutes.',
      'Add spinach and toss until just wilted.',
      'Add drained pasta, half the pasta water, lemon juice, and parmesan. Toss vigorously.',
      'Season with salt and red pepper flakes. Add more pasta water if needed.',
    ],
    cuisine: 'italian',
    mealType: 'dinner',
    dietary: ['vegetarian', 'nut_free', 'soy_free'],
    primaryProtein: 'none',
    cookingMethods: ['stovetop'],
    activeTimeMinutes: 15,
    totalTimeMinutes: 20,
    cookTimeBucket: '15_to_30_min',
    difficulty: 'easy',
    spiceLevel: 'mild',
    occasion: ['weeknight', 'budget_friendly'],
    servings: 4,
    popularityScore: 0.88,
  },
  {
    id: 1004,
    title: 'Classic French Omelette',
    imageUrl: 'https://images.unsplash.com/photo-1510693206972-df098062cb71?w=600',
    ingredients: [
      { name: 'eggs', quantity: 3, unit: 'large' },
      { name: 'butter', quantity: 1, unit: 'tbsp' },
      { name: 'salt', quantity: 0.25, unit: 'tsp' },
      { name: 'black pepper', quantity: 0.125, unit: 'tsp' },
    ],
    ingredientNames: ['eggs', 'butter', 'salt', 'black pepper'],
    instructions: [
      'Crack eggs into a bowl. Season with salt and pepper. Beat until just combined.',
      'Heat butter in an 8-inch non-stick pan over medium-high heat until foaming.',
      'Pour in eggs. Stir rapidly with a fork while shaking the pan for 30 seconds.',
      'When eggs are mostly set but still creamy on top, tilt pan and roll omelette onto plate.',
    ],
    cuisine: 'french',
    mealType: 'breakfast',
    alsoWorksAs: ['brunch', 'lunch'],
    dietary: ['vegetarian', 'gluten_free', 'nut_free', 'soy_free'],
    primaryProtein: 'eggs',
    cookingMethods: ['stovetop'],
    activeTimeMinutes: 5,
    totalTimeMinutes: 5,
    cookTimeBucket: 'under_15_min',
    difficulty: 'medium',
    spiceLevel: 'none',
    occasion: ['weeknight'],
    servings: 1,
    popularityScore: 0.85,
  },
  {
    id: 1005,
    title: 'Tomato Basil Bruschetta',
    imageUrl: 'https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=600',
    ingredients: [
      { name: 'tomatoes', quantity: 4, unit: 'medium' },
      { name: 'basil', quantity: 10, unit: 'leaves' },
      { name: 'garlic', quantity: 2, unit: 'cloves' },
      { name: 'olive oil', quantity: 3, unit: 'tbsp' },
      { name: 'balsamic vinegar', quantity: 1, unit: 'tbsp' },
      { name: 'salt', quantity: 0.5, unit: 'tsp' },
      { name: 'bread', quantity: 1, unit: 'baguette' },
    ],
    ingredientNames: ['tomatoes', 'basil', 'garlic', 'olive oil', 'balsamic vinegar', 'salt', 'bread'],
    instructions: [
      'Dice tomatoes and combine with torn basil, minced garlic, olive oil, and balsamic.',
      'Season with salt. Let marinate 15 minutes.',
      'Slice baguette, brush with olive oil, and toast until golden.',
      'Spoon tomato mixture onto toasted bread. Serve immediately.',
    ],
    cuisine: 'italian',
    mealType: 'appetizer',
    dietary: ['vegan', 'nut_free', 'soy_free'],
    primaryProtein: 'none',
    cookingMethods: ['no_cook', 'oven_bake'],
    activeTimeMinutes: 10,
    totalTimeMinutes: 25,
    cookTimeBucket: '15_to_30_min',
    difficulty: 'easy',
    spiceLevel: 'none',
    occasion: ['dinner_party', 'summer_seasonal'],
    servings: 6,
    popularityScore: 0.87,
  },
];

export function getMatchedRecipes(pantryNames: string[]) {
  const pantrySet = new Set(pantryNames.map(n => n.toLowerCase()));
  return MOCK_RECIPES.map(recipe => {
    const matched = recipe.ingredientNames.filter(n => pantrySet.has(n.toLowerCase()));
    const missed = recipe.ingredientNames.filter(n => !pantrySet.has(n.toLowerCase()));
    return {
      ...recipe,
      usedCount: matched.length,
      missedCount: missed.length,
      missedIngredients: missed,
    };
  }).sort((a, b) => b.usedCount - a.usedCount);
}
